"""
=============================================================
CIRO — Automated Markdown Report Generator
=============================================================
Runs the simulation runner, captures stdout, and writes a
beautifully styled Markdown trace log artifact in UTF-8.
=============================================================
"""

import sys
import io
import os
from run_simulation import reset_registry, CIROOrchestrator, DEFAULT_HOSPITALS

def generate_markdown_artifact():
    # Redirect stdout to capture all prints
    old_stdout = sys.stdout
    new_stdout = io.StringIO()
    sys.stdout = new_stdout

    # Run the three scenarios
    reset_registry()

    # Trigger Scenario 1: Severe accident at Clifton requiring a Ventilator
    print("Executing Scenario 1: Critical ventilator incident at Clifton...")
    orch_1 = CIROOrchestrator()
    trigger_1 = "Severe head-on accident near Clifton, patient suffocating and not breathing, requires ventilator immediately!"
    result_1 = orch_1.process_trigger(trigger_1)
    
    print("\n" + "="*80)
    print("                      SCENARIO 1: AGENT TRACE LOGS")
    print("="*80)
    for entry in result_1["event_log"]:
        print(f"[{entry['timestamp']}] | {entry['agent'].ljust(22)} | {entry['message']}")
    print("="*80 + "\n")

    # Trigger Scenario 2: Emergency at Gulshan, patient needs ICU
    print("\nExecuting Scenario 2: Serious ICU incident at Gulshan...")
    orch_2 = CIROOrchestrator()
    trigger_2 = "Cardiac chest pain event at Gulshan, patient unconscious, needs ICU admission"
    result_2 = orch_2.process_trigger(trigger_2)
    
    print("\n" + "="*80)
    print("                      SCENARIO 2: AGENT TRACE LOGS")
    print("="*80)
    for entry in result_2["event_log"]:
        print(f"[{entry['timestamp']}] | {entry['agent'].ljust(22)} | {entry['message']}")
    print("="*80 + "\n")

    # Trigger Scenario 3: Stable fracture at Nazimabad (basic bed)
    print("\nExecuting Scenario 3: Basic trauma incident at Nazimabad...")
    orch_3 = CIROOrchestrator()
    trigger_3 = "Road accident at Nazimabad, patient bleeding with minor arm fracture, is stable but needs general bed"
    result_3 = orch_3.process_trigger(trigger_3)
    
    print("\n" + "="*80)
    print("                      SCENARIO 3: AGENT TRACE LOGS")
    print("="*80)
    for entry in result_3["event_log"]:
        print(f"[{entry['timestamp']}] | {entry['agent'].ljust(22)} | {entry['message']}")
    print("="*80 + "\n")

    # Restore stdout
    sys.stdout = old_stdout
    output_log = new_stdout.getvalue()

    # Structure beautiful markdown file
    md_content = f"""# CIRO Emergency Rescue System — Multi-Agent Simulation Report

This report presents the shared state schema, environment tools, and automated trace execution logs generated by the **Google Antigravity** multi-agent orchestration workflow.

---

## 1. Shared State Schema
The system maintains a unified dataclass-driven `SystemState` shared between all agents:

- **PatientRequest**: Ingests emergency location, triage severity, status (`pending`, `dispatched`, `en_route`, `admitted`), and ICU/ventilator requirements.
- **AmbulanceState**: Tracks dynamic coordinates, active patient ID, selected hospital destination, and route polyline waypoints.
- **Hospital**: Registers capacity for general beds, ICU beds, mechanical ventilators, and trauma support status.

---

## 2. Environment Tools
The pipeline utilizes three native tools to interface with the state and execute actions:
1. `get_distance(coord1, coord2)`: Calculates Haversine distance and route ETAs.
2. `check_hospital_resources(hospital_id)`: Queries active bed, ICU, and ventilator capacity.
3. `reserve_bed(hospital_id, resource_type)`: Dynamically reserves a unit and decrements active registry counts.

---

## 3. Mock Hospital Registry (Initial Capacity)
| Hospital ID | Name | Available Beds | ICU Beds | Ventilators | Accepts Trauma |
|---|---|:---:|:---:|:---:|:---:|
| **HOSP-A** | Trauma Center Karachi | 5 | 0 | 0 | Yes |
| **HOSP-B** | City General Hospital | 12 | 3 | 1 | No |
| **HOSP-C** | City Medical Complex | 0 | 5 | 2 | No |
| **HOSP-D** | Jinnah Postgraduate Medical Centre | 20 | 10 | 5 | Yes |

---

## 4. Multi-Agent Execution Trace logs

```text
{output_log}
```

---
"""

    report_path = os.path.join(os.path.dirname(__file__), "simulation_trace_logs.md")
    with open(report_path, "w", encoding="utf-8") as f:
        f.write(md_content)
    print(f"[Reporter] Beautiful markdown report generated successfully at: {report_path}")

if __name__ == "__main__":
    generate_markdown_artifact()
